export const PERMISSIONS = {
  USER_READ: "USER_READ",
  USER_CREATE: "USER_CREATE",
  USER_UPDATE: "USER_UPDATE",
  USER_DELETE: "USER_DELETE",

  ROLE_READ: "ROLE_READ",
  ROLE_CREATE: "ROLE_CREATE",

  CONSULTATION_CREATE: "CONSULTATION_CREATE",
  CONSULTATION_VIEW: "CONSULTATION_VIEW",

  FEATURE_LIBRARY_MANAGE: "FEATURE_LIBRARY_MANAGE",

  PROPOSAL_CREATE: "PROPOSAL_CREATE",

  CRM_VIEW: "CRM_VIEW",
} as const;

export type PermissionCode =
  (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
